# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: baf60e61fb7902e801bf44484d1bd58ad6686d4b0a61a3257c6024be9dbd4fc46cfe4a40a201987c6e7074b1deed3cf3b967559e8960c8f72a86effbb054ed09

test:
  secret_key_base: ed084c5e0e0d9222d0e197fba0049dd6bce2b7d8f7d962962509e8bdde1df1eb1aa31c2b36721cbcddc42e33fd1f06d0a9e6f2393ae970156e92cb12a4c468e7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
